\encoding UTF8
\copy fornecedor(nome) FROM 'src/database/initialization/data/fornecedor.data.csv' WITH(FORMAT CSV)
\copy ingrediente(nome,qtd,codFor) FROM 'src/database/initialization/data/ingrediente.data.csv' WITH(FORMAT CSV)
\copy embalagem(nome,qtd,codFor) FROM 'src/database/initialization/data/embalagem.data.csv' WITH(FORMAT CSV)
\copy louca(nome,qtd,codFor) FROM 'src/database/initialization/data/louca.data.csv' WITH(FORMAT CSV)
\copy alimento(nome,codEmb,codLou,preco) FROM 'src/database/initialization/data/alimento.data.csv' WITH(FORMAT CSV)
\copy alimento_ingrediente(codAli,codIng,qtd) FROM 'src/database/initialization/data/ingrediente_alimento.data.csv' WITH(FORMAT CSV)
\copy bebida(codAli,qtd,codFor) FROM 'src/database/initialization/data/bebida.data.csv' WITH(FORMAT CSV)
\copy sobremesa(codAli) FROM 'src/database/initialization/data/sobremesa.data.csv' WITH(FORMAT CSV)
\copy prato(codAli) FROM 'src/database/initialization/data/prato.data.csv' WITH(FORMAT CSV)
\copy hamburguer(codAli) FROM 'src/database/initialization/data/hamburguer.data.csv' WITH(FORMAT CSV)
\copy funcionario(nome,codGer) FROM 'src/database/initialization/data/funcionarios.data.csv' WITH(FORMAT CSV)
\copy garcom(codFun) FROM 'src/database/initialization/data/garcom.data.csv' WITH(FORMAT CSV)
\copy entregador(codFun,cnh) FROM 'src/database/initialization/data/entregador.data.csv' WITH(FORMAT CSV)
\copy mesa(nome,nlugares,reservada,codGar) FROM 'src/database/initialization/data/mesa.data.csv' WITH(FORMAT CSV)
\copy cliente(nome,codMes,endereco,codEnt) FROM 'src/database/initialization/data/cliente.data.csv' WITH(FORMAT CSV)
\copy pedido(time) FROM 'src/database/initialization/data/pedido.data.csv' WITH(FORMAT CSV)
\copy pedido_alimento(codPed,codAli,qtd) FROM 'src/database/initialization/data/pedido_alimento.data.csv' WITH(FORMAT CSV)
\copy pedido_salao(codPed,codMes) FROM 'src/database/initialization/data/pedidoSalao.data.csv' WITH(FORMAT CSV)
\copy pedido_entrega(codPed,codCli) FROM 'src/database/initialization/data/pedidoEntrega.data.csv' WITH(FORMAT CSV)


